replicaCount: 1

auth:
  existingSecret: mysql-staging-auth

persistence:
  accessModes:
    - ReadWriteMany
  size: 10Gi
  storageClassName: nfs-storage

service:
  type: ClusterIP
  port: 3306

mysql:
    host: mysql
    database: app_db
    user: node-app-user
    password: node-app-password
    rootPassword: node-app-root-password