replicaCount: 1

auth:
  existingSecret: mysql-staging-auth

persistence:
  accessModes:
    - ReadWriteMany
  size: 10Gi
  storageClassName: nfs-storage

service:
  type: ClusterIP
  port: 3306

mysql:
    database: app_db
    user: appuser
    password: apppassword
    rootPassword: node-app-root-password