apiVersion: v1
kind: Secret
metadata:
  name: mysql-staging-auth
  namespace: node-app-staging
type: Opaque
stringData:
  MYSQL_DATABASE: appdb_staging
  MYSQL_USER: appuser
  MYSQL_PASSWORD: stagingpassword
  MYSQL_ROOT_PASSWORD: stagingrootpassword
