apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
        {{ .Release.Name }}: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-auth
    creationPolicy: Owner
  data:
    - secretKey: mysql_user
      remoteRef:
        key: dev/db-credential
        property: mysql_user

    - secretKey: mysql_password
      remoteRef:
        key: dev/db-credential
        property: mysql_password
