apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-dev-auth.authSecretName" . }}
  labels:
    {{- include "mysql-dev-auth.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.mysql.MYSQL_USER | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.MYSQL_PASSWORD | quote }}