apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    {{ .Release.Name }}: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.mysql.MYSQL_USER | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.MYSQL_PASSWORD | quote }}