apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-old
  labels:
    {{ .Release.Name }}: {{ .Release.Name }}
type: Opaque
stringData:
  mysql-user: {{ .Values.mysql.MYSQL_USER | quote }}
  mysql-password: {{ .Values.mysql.MYSQL_PASSWORD | quote }}