apiVersion: v1
kind: Secret
metadata:
  name: mysql-dev-auth
  namespace: node-app-dev
type: Opaque
stringData:
  MYSQL_DATABASE: appdb_dev
  MYSQL_USER: appuser
  MYSQL_PASSWORD: devpassword
  MYSQL_ROOT_PASSWORD: devrootpassword
