apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-staging-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohammedzuhair25/node-js-example-k8s.git
    targetRevision: main
    path: k8s/node-app-secrets/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: node-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
