apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-service-monitor
  namespace: monitoring
  labels:
    release: monitoring      # must match Prometheus serviceMonitorSelector
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: node
  namespaceSelector:
    matchNames:
    - node-app       # namespace of your service
  selector:
    matchLabels:
      app: node-app
