apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: node-swagger-metrics # name must be under the container
          image: mzm1/node-swagger-metrics:47611a47
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
