namespace: flyway-staging
image:
  repository: mzm1/flyway-migrations
  tag: "staging-d3c2ec91e42d5dc037a02641e0ff2d4a389644b4"
  pullPolicy: IfNotPresent
database:
  host: mysql-staging.mysql-staging.svc.cluster.local
  port: 3306
  name: app_db
  user: root
  password: "node-app-root-password"
secret:
  name: mysql-secret
  passwordKey: password
job:
  name: flyway-migration-staging
  restartPolicy: Never
  backoffLimit: 3
resourceQuota:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"
  pods: "10"
