namespace: default
image:
  repository: mzm1/flyway-migrations
  tag: "1.0.0"
  pullPolicy: IfNotPresent

database:
  host: mysql
  port: 3306
  name: app_db
  user: root
  password: "rootpassword"

secret:
  name: mysql-secret
  passwordKey: password

job:
  name: flyway-migration
  restartPolicy: Never
  backoffLimit: 3

resourceQuota:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"
  pods: "10"
