namespace: flyway-dev
image:
  repository: mzm1/flyway-migrations
  tag: "dev-a05461befe6626ee256db9b73f3e333bd4053ac5"
  pullPolicy: IfNotPresent

database:
  host: mysql-dev.mysql-dev.svc.cluster.local
  port: 3306
  name: app_db
  user: root
  password: "node-app-root-password"

secret:
  name: mysql-secret
  passwordKey: password

job:
  name: flyway-migration-dev
  restartPolicy: Never
  backoffLimit: 3

resourceQuota:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
  pods: "5"
