replicaCount: 1
image:
  repository: mzm1/node-swagger-metrics
  tag: 8e059f9a8973f72b135d05a93d566e2b0e13f072
service:
  type: NodePort
  port: 3000
  targetPort: 3000
container:
  port: 3000
env:
  NODE_ENV: development
ingress:
  host: dev.node-app.local
