replicaCount: 2
image:
  repository: mzm1/node-swagger-metrics
  tag: 098bfb24f53663fcf690556134a01dc17e2bd0b1
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
container:
  port: 3000
env:
  NODE_ENV: staging
database:
  host: mysql-staging.mysql-dev.svc.cluster.local
  port: 3306
  name: app_db
ingress:
  host: staging.node-app.local
mysql:
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
auth:
  existingSecret: ""
