replicaCount: 2

image:
  repository: mzm1/node-swagger-metrics
  tag: ee664c81

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

container:
  port: 3000

env:
  NODE_ENV: staging

envFromSecrets:
  - node-app-staging-mysql

ingress:
  host: staging.node-app.local
