replicaCount: 1
image:
  repository: mzm1/node-swagger-metrics
  tag: a90ceb1211f9f0b22aaa66c7cc9b60ac844eaa1b
service:
  type: NodePort
  port: 3000
  targetPort: 3000
container:
  port: 3000
env:
  NODE_ENV: development
ingress:
  host: dev.node-app.local
